daw/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

urlpatterns = [
    # Examples:
    # url(r'^$', 'daw.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    path('admin/', admin.site.urls),
    path('',include(('helpmapp.urls','helpmapp'), namespace='helpmapp'))
]

helpmapp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # For Everyone
    url(r'^$', views.mostrar_indice, name='mostrar_indice'),
    # url(r'^lol$', views.get_name),
    # url(r'^thanks/', views.show_name),
    url(r'^donar/', views.listar_centroAcopio, name="listar_centroAcopio"),
    #        url(r'^voluntario/', views.mostrar_voluntario,name="mostrar_voluntario"),
    url(r'^equipo/', views.mostrar_sobreNosotros, name="mostrar_sobreNosotros"),
    url(r'^login/', views.mostrar_login, name="mostrar_login"),
    url(r'^recovery/', views.recovery, name="recovery"),

    # For HelpMapper
    url(r'^home/', views.index_hm, name="index_hm"),
    url(r'^hm/donar/', views.listar_centroAcopioHM, name="listar_centroAcopioHM"),
    url(r'^hm/estadistica/', views.mostrar_GraficoEstadistico, name="mostrar_GraficoEstadistico"),
    url(r'^hm/tutoriales/', views.mostrar_tutoriales, name="mostrar_tutoriales"),
    url(r'^hm/equipo/', views.mostrar_sobreNosotrosHM, name="mostrar_sobreNosotrosHM"),
    url(r'^newPassword/', views.change_password, name="change_password"),

#    url(r'^listar/', views.listar_voluntario, name="listar_voluntario"),

    url(r'^loginAdmin/', views.mostrar_loginAdmin, name="mostrar_loginAdmin"),

    url(r'^administradorGeneral/$', views.mostrar_administradorGeneral, name="mostrar_administradorGeneral"),
    url(r'^administradorGeneral/buscarCentroAcopio/$', views.buscarCentroAcopio, name="buscarCentroAcopio"),
    url(r'^administradorGeneral/configuracionCuenta/$', views.mostrar_configCuenta, name="mostrar_configCuenta"),
    url(r'^administradorGeneral/crearAdmin/$', views.mostrar_crearAdministrador, name="mostrar_crearAdministrador"),
    url(r'^administradorGeneral/verCentro/(?P<id_centro>\d+)/$', views.mostrar_verCentro, name="mostrar_verCentro"),
    url(r'^administradorGeneral/crearProducto/$', views.mostrar_crearProducto, name="mostrar_crearProducto"),

    url(r'^administradorZonal/configuracionCapacidades/', views.mostrar_configuracionCapacidades,
        name="mostrar_configuracionCapacidades"),
    url(r'^administradorZonal/configuracionCuenta/', views.mostrar_configuracionCuenta,
        name="mostrar_configuracionCuenta"),  # de admin zonal

    url(r'^administradorZonal/inventarioAgua/', views.mostrar_inventarioAgua, name="mostrar_inventarioAgua"),
    url(r'^administradorZonal/inventarioComida/', views.mostrar_inventarioComida, name="mostrar_inventarioComida"),
    url(r'^administradorZonal/inventarioRopa/', views.mostrar_inventarioRopa, name="mostrar_inventarioRopa"),

    url(r'^administradorZonal/', views.mostrar_administradorZonal, name="mostrar_administrador_zonal"),

    url(r'^admin/recuperarCuenta', views.mostrar_recuperarCuenta, name="mostrar_recuperarCuenta"),

    url(r'^profile/(?P<nombre_usuario>\S+)$', views.profile, name='profile'),
    url(r'^logout/', views.logout, name="logout"),

    url(r'^cerrarSesion/', views.cerrarSesion, name="cerrarSesion"),

    # CRUD HelpMapper
    url(r'^voluntario/$', views.registrar_helpmapper, name='registrar_helpmapper'),
    # url(r'^voluntario/change_pass/$', views.actualizar_contrasena,name='actualizar_contrasena'),
    url(r'^voluntario/delete/$', views.eliminar_helpmapper, name='eliminar_helpmapper'),

    # Datos para graficos D3JS
    url(r'^datos/$', views.obtener_datos, name='obtener_datos'),

    # Datos para provincias
    # url(r'^datosProvincias/$', views.obtener_datosProvincias,name='obtener_datosProvincias'),
]

helpmapp/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms

from .models import *


class HelpMapperForm(forms.ModelForm):
    class Meta:
        model = HelpMapper
        fields = ('nombre', 'apellido', 'nombre_usuario', 'contrasena', 'sexo', 'cedula',
                  'tipo_sangre', 'telefono', 'correo', 'habilidad', 'estado')


class LoginForm(forms.Form):
    username = forms.CharField(label='Nombre de usuario', max_length=16)
    password = forms.CharField(widget=forms.PasswordInput, label='Nombre de usuario', max_length=16)


class RecoveryForm(forms.Form):
    correo = forms.CharField(label='Correo Electrónico', max_length=100, required=True)


class configurarCapacidadesForm(forms.Form):
    almacenamiento_agua = forms.DecimalField(label='Capacidad máxima de agua:', max_digits=8)
    almacenamiento_ropa = forms.DecimalField(label='Capacidad máxima de ropa:', max_digits=8)
    almacenamiento_comida = forms.DecimalField(label='Capacidad máxima de Comida:', max_digits=8)


class ChangePassForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput, label='Contrasena', max_length=16)
    confirm_password = forms.CharField(widget=forms.PasswordInput, label='Confirmar contrasena', max_length=16)


class ChangePassAdminForm(forms.Form):
    password_actual = forms.CharField(widget=forms.PasswordInput, label='Contrasena Actual', max_length=16)
    password = forms.CharField(widget=forms.PasswordInput, label='Contrasena', max_length=16)
    confirm_password = forms.CharField(widget=forms.PasswordInput, label='Confirmar contrasena', max_length=16)


class AdminForm(forms.ModelForm):
    class Meta:
        model = Administrador
        widgets = {
            'contrasena': forms.PasswordInput(),
        }
        fields = ('nombre_usuario', 'contrasena', 'correo')


class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ('nombre_producto', 'id_categoria')


class filtroForm(forms.Form):
    provincia = forms.CharField()
    ciudad = forms.CharField()


class ExistenciaInventarioForm(forms.ModelForm):
    class Meta:
        model = ExistenciaInventario
        fields = ('id_producto', 'id_centro', 'cantidad')


class CoordenadasForm(forms.Form):
    latitud = forms.DecimalField(max_digits=8)
    longitud = forms.DecimalField(max_digits=8)

helpmapp/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import json
import random
import string

from django.contrib import messages
from django.core.mail import send_mail
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect

from daw.settings import EMAIL_HOST_USER
from .forms import *
from .models import *


# Decorator for authentication.
def authenticated(func):
    """
    Receives a django view function and decorates it with an session cookie check
    :param func:
    :return:
    """

    def _wrapped_func(*args, **kwargs):
        request = args[0]
        if 'member_id' in request.session:
            return func(*args, **kwargs)
        else:
            return redirect('/')

    return _wrapped_func


# Controllers for everyone
def mostrar_indice(request):
    return render(request, 'helpmapp/cliente/not_logged/index.html')


# devolver todos los centros de acopios
def listar_centroAcopio(request):
    centros = CentroDeAcopio.objects.all()
    if request.method == 'POST':
        form = coordenadasForm(request.POST)
        data = form.cleaned_data
        if form.is_valid():
            latitud = data['latitud']
            longitud = data['longitud']
            return render(request, 'helpmapp/cliente/not_logged/donar.html',
                          {'centros': centros, 'latitud': latitud, 'longitud': longitud})
    return render(request, 'helpmapp/cliente/not_logged/donar.html', {'centros': centros})


def mostrar_sobreNosotros(request):
    return render(request, 'helpmapp/cliente/not_logged/aboutus.html')


def mostrar_login(request):
    if "member_id" not in request.session.keys():
        if request.method == 'POST':
            form = LoginForm(request.POST)
            if form.is_valid():
                try:
                    m = HelpMapper.objects.get(nombre_usuario=request.POST['username'])
                    print(m.contrasena == request.POST['password'])
                    if m.contrasena == request.POST['password']:
                        request.session['member_id'] = m.nombre_usuario
                        print(request.session['member_id'])
                        return HttpResponseRedirect('/home/')
                    else:
                        messages.error(request, "Credenciales incorrectas")
                except:
                    messages.error(request, "Usuario no registrado")
            else:
                form = LoginForm()
        else:
            form = LoginForm()
            print(form)
        return render(request, 'helpmapp/cliente/not_logged/login.html', {'form': form})
    else:
        print(request.session['member_id'])
        usuario = HelpMapper.objects.get(nombre_usuario=request.session['member_id'])
        return render(request, 'helpmapp/cliente/helpmapper/index.html', {'usuario': usuario})


def id_generator(size=6, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

@authenticated
def recovery(request):
    if request.method == 'GET':
        form = RecoveryForm()
        return render(request, 'helpmapp/cliente/not_logged/recovery.html', {'form': form})

    elif request.method == 'POST':
        # send_mail("Cambio de contrasena", "Post", EMAIL_HOST_USER, ['ramsesfabri@gmail.com]'],fail_silently=False)

        # create a form instance and populate it with data from the request:
        form = RecoveryForm(request.POST)
        print(request.POST)
        developers = ["Fabricio", "Galo", "María Belén", "Jonathan"]

        # check whether it's valid:
        if form.is_valid():
            print("is valid")

            # process the data in form.cleaned_data as required      
            # redirect to a new URL:
            data = form.cleaned_data

            try:
                hm = HelpMapper.objects.get(correo=data['correo'])
                if data['correo'] == hm.correo:
                    print("ENVIANDO...")
                    remiter = developers[random.randint(0, len(
                        developers) - 1)] + " del Equipo de helpMapp, te saluda e informa que: \n"
                    text = remiter + "Tu cambio de contraseña ha sido exitoso. Por favor, ingresa con tu nueva contraseña: "
                    new_contrasena = id_generator(8)
                    text += new_contrasena + "\n" + "Gracias por ser un helpMapper!"

                    hm.contrasena = new_contrasena
                    hm.save()
                    # send_mail("Vales trozo", text, EMAIL_HOST_USER, ['rodfcast@gmail.com]'],fail_silently=False)
                    send_mail("helpMapp: Cambio de contraseña", text, EMAIL_HOST_USER, [data['correo']],
                              fail_silently=False)
                    return render(request, 'helpmapp/cliente/not_logged/message.html', {'title': 'Correo Enviado',
                                                                                        'message': 'Su nueva contraseña ha sido enviada al correo registrado.'})
            except Exception as e:
                return render(request, 'helpmapp/cliente/not_logged/message.html',
                              {'title': 'Correo Inválido', 'message': 'El correo ingresado es incorrecto.'})
                pass
    return render(request, 'helpmapp/cliente/not_logged/message.html', {'form': form})

@authenticated
def index_hm(request):
    return render(request, 'helpmapp/cliente/helpmapper/index.html')


# devolver todos los centros de acopios
@authenticated
def listar_centroAcopioHM(request):
    centros = CentroDeAcopio.objects.all()

    return render(request, 'helpmapp/cliente/helpmapper/donar.html', {'centros': centros})


# estadistica Grafico pra cliente
def mostrar_GraficoEstadistico(request):
    # comida=Producto.objects.filter(id_categoria=1) #id de comida
    # kg=0
    # for c in comida:
    #     kg+=c.cantidad
    # ropas=Producto.objects.filter(id_categoria=2) # id de ropa
    # ropa=0
    # for r in ropas:
    #     ropa+=r.cantidad
    # agua=Producto.objects.filter(id_categoria=3) #id de agua
    # l=0
    # for a in agua:
    #     l+=a.cantidad
    # lista2=[]
    # lista2.append(float(kg))
    # lista2.append(float(ropa))
    # lista2.append(float(l))
    # print (lista2)
    # #lista=json.dumps(lista2)
    # lista=lista2
    return render(request, 'helpmapp/cliente/helpmapper/statistics.html')


def mostrar_tutoriales(request):
    return render(request, 'helpmapp/cliente/helpmapper/tutoriales.html')

@authenticated
def mostrar_sobreNosotrosHM(request):
    return render(request, 'helpmapp/cliente/helpmapper/aboutus.html')

### TODO: Arreglar este endpoint.
def listar_voluntario(request):
    voluntarios = AyudadorMapa.objects.all()

    return render(request, 'helpmapp/cliente/prueba.html', {'voluntarios': voluntarios})


def crear_voluntario(request):
    if request.method == 'POST':
        form = VoluntaryForm(request.POST)
        if form.is_valid():
            voluntario = form.save(commit=False)
            voluntario.save()
            return render(request, 'helpmapp/cliente/voluntario.html', {'form': form})
        else:
            print('no es valido')

    else:
        form = VoluntaryForm()

    return render(request, 'helpmapp/cliente/voluntario.html', {'form': form})


def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = VoluntaryForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required

            # redirect to a new URL:
            data = form.cleaned_data
            print(data['nombre'])
            print(data['apellido'])
            print(data['cedula'])
            # print data['GENDER_CHOICES']
            print(data['trabajo_campo'])
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = VoluntaryForm()

    return render(request, 'helpmapp/voluntario.html', {'form': form})


def show_name(request):
    return render(request, 'helpmapp/prueba.html')


# LOGIN DEL ADMINISTRADOR
def mostrar_loginAdmin(request):
    if (not "member_id" in request.session.keys()):
        if request.method == 'POST':
            form = LoginForm(request.POST)
            if form.is_valid():
                try:
                    m = Administrador.objects.get(nombre_usuario=request.POST['username'])
                    print(m.contrasena == request.POST['password'])
                    if m.contrasena == request.POST['password']:
                        request.session['member_id'] = m.nombre_usuario
                        request.session['tipo'] = m.tipo
                        if (m.tipo == 0):  # es super admin
                            centros = CentroDeAcopio.objects.all()
                            comida = Producto.objects.filter(id_categoria=1)  # id de comida
                            kg = 0
                            for c in comida:
                                productos = ExistenciaInventario.objects.filter(id_producto=c.id)
                                for p in productos:
                                    kg += p.cantidad

                            ropas = Producto.objects.filter(id_categoria=2)  # id de ropa
                            ropa = 0
                            for r in ropas:
                                productos = ExistenciaInventario.objects.filter(id_producto=r.id)
                                for p in productos:
                                    ropa += p.cantidad
                            aguas = Producto.objects.filter(id_categoria=3)  # id de agua
                            agua = 0
                            for a in aguas:

helpmapp/templates/helpmapp/cliente/not_logged/aboutus.html
{% extends "helpmapp/cliente/bases/aboutus.html" %}
{% load static %}
{% block menu%}
  <!--AQUI VA UN CSRF PARA RECOGER EL NOMBRE DEL USUARIO Y LA SESION-->
  <li><a class="labels h4 " href="{% url 'helpmapp:mostrar_indice' %}"> Inicio </a></li>
  <li ><a class="labels h4 " href="{% url 'helpmapp:listar_centroAcopio' %}" > Donar</a></li>
  <li><a class="labels h4 " href="{% url 'helpmapp:registrar_helpmapper' %}" > Voluntario</a></li>-->
  <li ><a class="labels h4 " href="{% url 'helpmapp:mostrar_sobreNosotros' %}"> Sobre Nosotros</a> </li>
  <li ><a class="labels h4 " href="{% url 'helpmapp:mostrar_login' %}"> Ingresar</a> </li>
{% endblock %}

helpmapp/templates/helpmapp/cliente/not_logged/donar.html
{% extends "helpmapp/cliente/bases/donar.html" %}
{% load static %}
{% block menu%}
  <!--AQUI VA UN CSRF PARA RECOGER EL NOMBRE DEL USUARIO Y LA SESION-->
  <li><a class="labels h4 " href="{% url 'helpmapp:mostrar_indice' %}"> Inicio </a></li>
  <li ><a class="labels h4 " href="{% url 'helpmapp:listar_centroAcopio' %}" > Donar</a></li>
  <li><a class="labels h4 " href="{% url 'helpmapp:registrar_helpmapper' %}" > Voluntario</a></li>-->
 

  <li ><a class="labels h4 " href="{% url 'helpmapp:mostrar_sobreNosotros' %}"> Sobre Nosotros</a> </li>
  <li ><a class="labels h4 " href="{% url 'helpmapp:mostrar_login' %}"> Ingresar</a> </li>
{% endblock %}

helpmapp/templates/helpmapp/cliente/not_logged/index.html
{% extends "helpmapp/cliente/bases/index.html" %}

{% load static %}

{% block menu%}
  <!--AQUI VA UN CSRF PARA RECOGER EL NOMBRE DEL USUARIO Y LA SESION-->
  <li><a class="labels h4 " href="{% url 'helpmapp:mostrar_indice' %}"> Inicio </a></li>
  <li ><a class="labels h4 " href="{% url 'helpmapp:listar_centroAcopio' %}" > Donar</a></li><!--
  <li><a class="labels h4 " href="{% url 'helpmapp:mostrar_GraficoEstadistico' %}"> Estadísticas</a></li>
  -->
  <li><a class="labels h4 " href="{% url 'helpmapp:registrar_helpmapper' %}" > Voluntario</a></li>-->
  <!--
  <li><a class="labels h4 " href="{% url 'helpmapp:mostrar_tutoriales' %}"> Tutoriales </a></li
  -->
  >
  <li ><a class="labels h4 " href="{% url 'helpmapp:mostrar_sobreNosotros' %}"> Sobre Nosotros</a> </li>
  <li ><a class="labels h4 " href="{% url 'helpmapp:mostrar_login' %}"> Ingresar</a> </li>
{% endblock %}

helpmapp/templates/helpmapp/cliente/not_logged/login.html
{% extends "helpmapp/cliente/bases/base.html" %}

{% load static %}

{% block title %}helpMapp - Recovering Password {% endblock %}

{% block css %}
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
    <link href="{% static 'styles/message.css' %}" rel="stylesheet">

{% endblock %}
{% block menu%}
  <!--AQUI VA UN CSRF PARA RECOGER EL NOMBRE DEL USUARIO Y LA SESION-->
  <li><a class="labels h4 " href="{% url 'helpmapp:mostrar_indice' %}"> Inicio </a></li>
  <li ><a class="labels h4 " href="{% url 'helpmapp:listar_centroAcopio' %}" > Donar</a></li>
  <li><a class="labels h4 " href="{% url 'helpmapp:registrar_helpmapper' %}" > Voluntario</a></li>
  <li ><a class="labels h4 " href="{% url 'helpmapp:mostrar_sobreNosotros' %}"> Sobre Nosotros</a> </li>
  <li ><a class="labels h4 " href="{% url 'helpmapp:mostrar_login' %}"> Ingresar</a> </li>
{% endblock %}
{% block body %}
<div class="top"></div>
	<div class="container">
		
		<div id="square">
			<img src="{% static 'img/helpMapp.jpg' %}">

			<div class="login-box">
				<hr class="featurette-divider">
				<form method="Post" class="form-horizontal formLogin" action="{% url 'helpmapp:mostrar_login' %}">
        			{% csrf_token %}
					<div class="row">
						<div class="col-md-5">
							<!--hr class="featurette-divider"-->
							<label class = 'h4 pt-20 title_message' for="username">Usuario</label>
						</div>	

						<!--hr class="featurette-divider"-->
						<div class="col-md-7">
							{{ form.username }}
						</div>
					</div>
					<div class="row">
						<div class="col-md-5">
							<!--hr class="featurette-divider"-->
							<label class = 'h4 pt-20 title_message' for="password">Contraseña</label>
						</div>	

						<!--hr class="featurette-divider"-->
						<div class="col-md-7">
							{{ form.password }}
						</div>
					</div>


					<hr class="featurette-divider">
					<div class="box-footer">
						<button type="submit" class="pt-20">Entrar!</button>
						<a  href="{% url 'helpmapp:recovery'%}" class="small link"><p  id="link-recover">¿Olvidaste tu contraseña?</p></a>
					</form>

				</div>
			</div>
		</div>
	</div>

	
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/login.js' %}"></script>
    <script src="{% static 'js/client/recover.js' %}"></script>

{% endblock %}

helpmapp/templates/helpmapp/cliente/not_logged/message.html
{% extends "helpmapp/cliente/bases/base.html" %}

{% load static %}

{% block title %}helpMapp - Message {% endblock %}

{% block css %}
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
    <link href="{% static 'styles/message.css' %}" rel="stylesheet">

{% endblock %}
{% block menu%}
  <!--AQUI VA UN CSRF PARA RECOGER EL NOMBRE DEL USUARIO Y LA SESION-->
  <li><a class="labels h4 " href="{% url 'helpmapp:mostrar_indice' %}"> Inicio </a></li>
  <li ><a class="labels h4 " href="{% url 'helpmapp:listar_centroAcopio' %}" > Donar</a></li>
  <li><a class="labels h4 " href="{% url 'helpmapp:registrar_helpmapper' %}" > Voluntario</a></li>
  <li ><a class="labels h4 " href="{% url 'helpmapp:mostrar_sobreNosotros' %}"> Sobre Nosotros</a> </li>
  <li ><a class="labels h4 " href="{% url 'helpmapp:mostrar_login' %}"> Ingresar</a> </li>
{% endblock %}
{% block body %}
<div class="top"></div>
	<div class="container">
		<div id="square">
			<img src="{% static 'img/helpMapp.jpg' %}">

			<div class="login-box">
				{% csrf_token %}
				<h4 class = 'center pt-20 title_message'>{{title}}</h4>
				<hr class="featurette-divider">
				<h5 class = 'message mt-30'>{{message}}</h5>
				<hr class="featurette-divider">
				<a  href="{% url 'helpmapp:mostrar_login'%}" class="small link"><h5 id="link-recover">Ingresar</h5></a>

			</div>
		</div>
	</div>

	
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/login.js' %}"></script>
    <script src="{% static 'js/client/recover.js' %}"></script>

{% endblock %}

helpmapp/templates/helpmapp/cliente/not_logged/recovery.html
{% extends "helpmapp/cliente/bases/base.html" %}

{% load static %}

{% block title %}helpMapp - Login {% endblock %}

{% block css %}
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
    <link href="{% static 'styles/message.css' %}" rel="stylesheet">

{% endblock %}
{% block menu%}
  <!--AQUI VA UN CSRF PARA RECOGER EL NOMBRE DEL USUARIO Y LA SESION-->
  <li><a class="labels h4 " href="{% url 'helpmapp:mostrar_indice' %}"> Inicio </a></li>
  <li ><a class="labels h4 " href="{% url 'helpmapp:listar_centroAcopio' %}" > Donar</a></li>
  <li><a class="labels h4 " href="{% url 'helpmapp:registrar_helpmapper' %}" > Voluntario</a></li>
  
  <li ><a class="labels h4 " href="{% url 'helpmapp:mostrar_sobreNosotros' %}"> Sobre Nosotros</a> </li>
  <li ><a class="labels h4 " href="{% url 'helpmapp:mostrar_login' %}"> Ingresar</a> </li>
{% endblock %}
{% block body %}
<div class="top"></div>
<div class="container">
	
	<div>
		<img src="{% static 'img/helpMapp.jpg' %}">

		<div class="recover-box">

			<form class= "loginbox" method="POST">
				{% csrf_token %}
				<hr class="featurette-divider">
				<label class = 'h4 center pt-20 title_message' for="mail">Correo Electrónico</label></h3>
				<!--hr class="featurette-divider"-->
				<h4 class = 'message mt-30'>Ingresa el correo con el que registraste para recuperar tu contraseña:</h4>
				<div id = "campo" class = 'mt-30'>{{form.correo}}</div>
				<!--hr class="featurette-divider"-->
				<hr class="featurette-divider">
				<button disabled = "disabled" type="submit" id="enviar" value="Enviar" href="{% url 'helpmapp:mostrar_login' %}">Enviar</button>
			</form>
		</div>
	</div>
</div>

	
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/login.js' %}"></script>
    <script src="{% static 'js/client/recover.js' %}"></script>

{% endblock %}