daw/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

urlpatterns = [
    # Examples:
    # url(r'^$', 'daw.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    path('admin/', admin.site.urls),
    path('',include(('helpmapp.urls','helpmapp'), namespace='helpmapp'))
]

helpmapp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # For Everyone
    url(r'^$', views.mostrar_indice, name='mostrar_indice'),
    # url(r'^lol$', views.get_name),
    # url(r'^thanks/', views.show_name),
    url(r'^donar/', views.listar_centroAcopio, name="listar_centroAcopio"),
    #        url(r'^voluntario/', views.mostrar_voluntario,name="mostrar_voluntario"),
    url(r'^equipo/', views.mostrar_sobreNosotros, name="mostrar_sobreNosotros"),
    url(r'^login/', views.mostrar_login, name="mostrar_login"),
    url(r'^recovery/', views.recovery, name="recovery"),

    # For HelpMapper
    url(r'^home/', views.index_hm, name="index_hm"),
    url(r'^hm/donar/', views.listar_centroAcopioHM, name="listar_centroAcopioHM"),
    url(r'^hm/estadistica/', views.mostrar_GraficoEstadistico, name="mostrar_GraficoEstadistico"),
    url(r'^hm/tutoriales/', views.mostrar_tutoriales, name="mostrar_tutoriales"),
    url(r'^hm/equipo/', views.mostrar_sobreNosotrosHM, name="mostrar_sobreNosotrosHM"),
    url(r'^newPassword/', views.change_password, name="change_password"),

#    url(r'^listar/', views.listar_voluntario, name="listar_voluntario"),

    url(r'^loginAdmin/', views.mostrar_loginAdmin, name="mostrar_loginAdmin"),

    url(r'^administradorGeneral/$', views.mostrar_administradorGeneral, name="mostrar_administradorGeneral"),
    url(r'^administradorGeneral/buscarCentroAcopio/$', views.buscarCentroAcopio, name="buscarCentroAcopio"),
    url(r'^administradorGeneral/configuracionCuenta/$', views.mostrar_configCuenta, name="mostrar_configCuenta"),
    url(r'^administradorGeneral/crearAdmin/$', views.mostrar_crearAdministrador, name="mostrar_crearAdministrador"),
    url(r'^administradorGeneral/verCentro/(?P<id_centro>\d+)/$', views.mostrar_verCentro, name="mostrar_verCentro"),
    url(r'^administradorGeneral/crearProducto/$', views.mostrar_crearProducto, name="mostrar_crearProducto"),

    url(r'^administradorZonal/configuracionCapacidades/', views.mostrar_configuracionCapacidades,
        name="mostrar_configuracionCapacidades"),
    url(r'^administradorZonal/configuracionCuenta/', views.mostrar_configuracionCuenta,
        name="mostrar_configuracionCuenta"),  # de admin zonal

    url(r'^administradorZonal/inventarioAgua/', views.mostrar_inventarioAgua, name="mostrar_inventarioAgua"),
    url(r'^administradorZonal/inventarioComida/', views.mostrar_inventarioComida, name="mostrar_inventarioComida"),
    url(r'^administradorZonal/inventarioRopa/', views.mostrar_inventarioRopa, name="mostrar_inventarioRopa"),

    url(r'^administradorZonal/', views.mostrar_administradorZonal, name="mostrar_administrador_zonal"),

    url(r'^admin/recuperarCuenta', views.mostrar_recuperarCuenta, name="mostrar_recuperarCuenta"),

    url(r'^profile/(?P<nombre_usuario>\S+)$', views.profile, name='profile'),
    url(r'^logout/', views.logout, name="logout"),

    url(r'^cerrarSesion/', views.cerrarSesion, name="cerrarSesion"),

    # CRUD HelpMapper
    url(r'^voluntario/$', views.registrar_helpmapper, name='registrar_helpmapper'),
    # url(r'^voluntario/change_pass/$', views.actualizar_contrasena,name='actualizar_contrasena'),
    url(r'^voluntario/delete/$', views.eliminar_helpmapper, name='eliminar_helpmapper'),

    # Datos para graficos D3JS
    url(r'^datos/$', views.obtener_datos, name='obtener_datos'),

    # Datos para provincias
    # url(r'^datosProvincias/$', views.obtener_datosProvincias,name='obtener_datosProvincias'),
]

helpmapp/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms

from .models import *


class HelpMapperForm(forms.ModelForm):
    class Meta:
        model = HelpMapper
        fields = ('nombre', 'apellido', 'nombre_usuario', 'contrasena', 'sexo', 'cedula',
                  'tipo_sangre', 'telefono', 'correo', 'habilidad', 'estado')


class LoginForm(forms.Form):
    username = forms.CharField(label='Nombre de usuario', max_length=16)
    password = forms.CharField(widget=forms.PasswordInput, label='Nombre de usuario', max_length=16)


class RecoveryForm(forms.Form):
    correo = forms.CharField(label='Correo Electrónico', max_length=100, required=True)


class configurarCapacidadesForm(forms.Form):
    almacenamiento_agua = forms.DecimalField(label='Capacidad máxima de agua:', max_digits=8)
    almacenamiento_ropa = forms.DecimalField(label='Capacidad máxima de ropa:', max_digits=8)
    almacenamiento_comida = forms.DecimalField(label='Capacidad máxima de Comida:', max_digits=8)


class ChangePassForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput, label='Contrasena', max_length=16)
    confirm_password = forms.CharField(widget=forms.PasswordInput, label='Confirmar contrasena', max_length=16)


class ChangePassAdminForm(forms.Form):
    password_actual = forms.CharField(widget=forms.PasswordInput, label='Contrasena Actual', max_length=16)
    password = forms.CharField(widget=forms.PasswordInput, label='Contrasena', max_length=16)
    confirm_password = forms.CharField(widget=forms.PasswordInput, label='Confirmar contrasena', max_length=16)


class AdminForm(forms.ModelForm):
    class Meta:
        model = Administrador
        widgets = {
            'contrasena': forms.PasswordInput(),
        }
        fields = ('nombre_usuario', 'contrasena', 'correo')


class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ('nombre_producto', 'id_categoria')


class filtroForm(forms.Form):
    provincia = forms.CharField()
    ciudad = forms.CharField()


class ExistenciaInventarioForm(forms.ModelForm):
    class Meta:
        model = ExistenciaInventario
        fields = ('id_producto', 'id_centro', 'cantidad')


class CoordenadasForm(forms.Form):
    latitud = forms.DecimalField(max_digits=8)
    longitud = forms.DecimalField(max_digits=8)

helpmapp/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import json
import random
import string

from django.contrib import messages
from django.core.mail import send_mail
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect

from daw.settings import EMAIL_HOST_USER
from .forms import *
from .models import *


# Decorator for authentication.
def authenticated(func):
    """
    Receives a django view function and decorates it with an session cookie check
    :param func:
    :return:
    """

    def _wrapped_func(*args, **kwargs):
        request = args[0]
        if 'member_id' in request.session:
            return func(*args, **kwargs)
        else:
            return redirect('/')

    return _wrapped_func


# Controllers for everyone
def mostrar_indice(request):
    return render(request, 'helpmapp/cliente/not_logged/index.html')


# devolver todos los centros de acopios
def listar_centroAcopio(request):
    centros = CentroDeAcopio.objects.all()
    if request.method == 'POST':
        form = coordenadasForm(request.POST)
        data = form.cleaned_data
        if form.is_valid():
            latitud = data['latitud']
            longitud = data['longitud']
            return render(request, 'helpmapp/cliente/not_logged/donar.html',
                          {'centros': centros, 'latitud': latitud, 'longitud': longitud})
    return render(request, 'helpmapp/cliente/not_logged/donar.html', {'centros': centros})


def mostrar_sobreNosotros(request):
    return render(request, 'helpmapp/cliente/not_logged/aboutus.html')


def mostrar_login(request):
    if "member_id" not in request.session.keys():
        if request.method == 'POST':
            form = LoginForm(request.POST)
            if form.is_valid():
                try:
                    m = HelpMapper.objects.get(nombre_usuario=request.POST['username'])
                    print(m.contrasena == request.POST['password'])
                    if m.contrasena == request.POST['password']:
                        request.session['member_id'] = m.nombre_usuario
                        print(request.session['member_id'])
                        return HttpResponseRedirect('/home/')
                    else:
                        messages.error(request, "Credenciales incorrectas")
                except:
                    messages.error(request, "Usuario no registrado")
            else:
                form = LoginForm()
        else:
            form = LoginForm()
            print(form)
        return render(request, 'helpmapp/cliente/not_logged/login.html', {'form': form})
    else:
        print(request.session['member_id'])
        usuario = HelpMapper.objects.get(nombre_usuario=request.session['member_id'])
        return render(request, 'helpmapp/cliente/helpmapper/index.html', {'usuario': usuario})


def id_generator(size=6, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

@authenticated
def recovery(request):
    if request.method == 'GET':
        form = RecoveryForm()
        return render(request, 'helpmapp/cliente/not_logged/recovery.html', {'form': form})

    elif request.method == 'POST':
        # send_mail("Cambio de contrasena", "Post", EMAIL_HOST_USER, ['ramsesfabri@gmail.com]'],fail_silently=False)

        # create a form instance and populate it with data from the request:
        form = RecoveryForm(request.POST)
        print(request.POST)
        developers = ["Fabricio", "Galo", "María Belén", "Jonathan"]

        # check whether it's valid:
        if form.is_valid():
            print("is valid")

            # process the data in form.cleaned_data as required      
            # redirect to a new URL:
            data = form.cleaned_data

            try:
                hm = HelpMapper.objects.get(correo=data['correo'])
                if data['correo'] == hm.correo:
                    print("ENVIANDO...")
                    remiter = developers[random.randint(0, len(
                        developers) - 1)] + " del Equipo de helpMapp, te saluda e informa que: \n"
                    text = remiter + "Tu cambio de contraseña ha sido exitoso. Por favor, ingresa con tu nueva contraseña: "
                    new_contrasena = id_generator(8)
                    text += new_contrasena + "\n" + "Gracias por ser un helpMapper!"

                    hm.contrasena = new_contrasena
                    hm.save()
                    # send_mail("Vales trozo", text, EMAIL_HOST_USER, ['rodfcast@gmail.com]'],fail_silently=False)
                    send_mail("helpMapp: Cambio de contraseña", text, EMAIL_HOST_USER, [data['correo']],
                              fail_silently=False)
                    return render(request, 'helpmapp/cliente/not_logged/message.html', {'title': 'Correo Enviado',
                                                                                        'message': 'Su nueva contraseña ha sido enviada al correo registrado.'})
            except Exception as e:
                return render(request, 'helpmapp/cliente/not_logged/message.html',
                              {'title': 'Correo Inválido', 'message': 'El correo ingresado es incorrecto.'})
                pass
    return render(request, 'helpmapp/cliente/not_logged/message.html', {'form': form})

@authenticated
def index_hm(request):
    return render(request, 'helpmapp/cliente/helpmapper/index.html')


# devolver todos los centros de acopios
@authenticated
def listar_centroAcopioHM(request):
    centros = CentroDeAcopio.objects.all()

    return render(request, 'helpmapp/cliente/helpmapper/donar.html', {'centros': centros})


# estadistica Grafico pra cliente
def mostrar_GraficoEstadistico(request):
    # comida=Producto.objects.filter(id_categoria=1) #id de comida
    # kg=0
    # for c in comida:
    #     kg+=c.cantidad
    # ropas=Producto.objects.filter(id_categoria=2) # id de ropa
    # ropa=0
    # for r in ropas:
    #     ropa+=r.cantidad
    # agua=Producto.objects.filter(id_categoria=3) #id de agua
    # l=0
    # for a in agua:
    #     l+=a.cantidad
    # lista2=[]
    # lista2.append(float(kg))
    # lista2.append(float(ropa))
    # lista2.append(float(l))
    # print (lista2)
    # #lista=json.dumps(lista2)
    # lista=lista2
    return render(request, 'helpmapp/cliente/helpmapper/statistics.html')


def mostrar_tutoriales(request):
    return render(request, 'helpmapp/cliente/helpmapper/tutoriales.html')

@authenticated
def mostrar_sobreNosotrosHM(request):
    return render(request, 'helpmapp/cliente/helpmapper/aboutus.html')

### TODO: Arreglar este endpoint.
def listar_voluntario(request):
    voluntarios = AyudadorMapa.objects.all()

    return render(request, 'helpmapp/cliente/prueba.html', {'voluntarios': voluntarios})


def crear_voluntario(request):
    if request.method == 'POST':
        form = VoluntaryForm(request.POST)
        if form.is_valid():
            voluntario = form.save(commit=False)
            voluntario.save()
            return render(request, 'helpmapp/cliente/voluntario.html', {'form': form})
        else:
            print('no es valido')

    else:
        form = VoluntaryForm()

    return render(request, 'helpmapp/cliente/voluntario.html', {'form': form})


def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = VoluntaryForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required

            # redirect to a new URL:
            data = form.cleaned_data
            print(data['nombre'])
            print(data['apellido'])
            print(data['cedula'])
            # print data['GENDER_CHOICES']
            print(data['trabajo_campo'])
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = VoluntaryForm()

    return render(request, 'helpmapp/voluntario.html', {'form': form})


def show_name(request):
    return render(request, 'helpmapp/prueba.html')


# LOGIN DEL ADMINISTRADOR
def mostrar_loginAdmin(request):
    if (not "member_id" in request.session.keys()):
        if request.method == 'POST':
            form = LoginForm(request.POST)
            if form.is_valid():
                try:
                    m = Administrador.objects.get(nombre_usuario=request.POST['username'])
                    print(m.contrasena == request.POST['password'])
                    if m.contrasena == request.POST['password']:
                        request.session['member_id'] = m.nombre_usuario
                        request.session['tipo'] = m.tipo
                        if (m.tipo == 0):  # es super admin
                            centros = CentroDeAcopio.objects.all()
                            comida = Producto.objects.filter(id_categoria=1)  # id de comida
                            kg = 0
                            for c in comida:
                                productos = ExistenciaInventario.objects.filter(id_producto=c.id)
                                for p in productos:
                                    kg += p.cantidad

                            ropas = Producto.objects.filter(id_categoria=2)  # id de ropa
                            ropa = 0
                            for r in ropas:
                                productos = ExistenciaInventario.objects.filter(id_producto=r.id)
                                for p in productos:
                                    ropa += p.cantidad
                            aguas = Producto.objects.filter(id_categoria=3)  # id de agua
                            agua = 0
                            for a in aguas:

helpmapp/templates/helpmapp/Administrador/superAdmin/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/estilo.css' %}" rel="stylesheet">
    <link href="{% static 'css/index-estilo.css' %}" rel="stylesheet">


    {% block css %}{% endblock %}

    
  </head>
  <body>

  <header>
    <div class="container col-md-12 header">
      <div >
        <div class="col-sm-4 col-sm-offset-4" id="logoDiv" >
          <img src="{% static 'img/helpmappLogo.png' %}" alt="logo">
        <a href="{% url 'helpmapp:mostrar_administradorGeneral' %}">

        </div>
        
          <div class="col-md-2 col-md-offset-2 logout">
          <p id="pe-logout">
          <span class="pull-left showopacity glyphicon glyphicon-off"></span>
           <a href="{% url 'helpmapp:cerrarSesion' %}"> Cerrar sesi&oacute;n</a>
          </p>
        </div>

        
      </div>
     <div class="row">
        <div id="titleId"  class="col-md-4 col-md-offset-4">
          <h2 id="cabecera">
            Sistema de administraci&oacute;n
          </h2>  
        </div>
        
      </div>

      <div class="row">
        <hr>
      </div>
    </div>    

  </header>
  <div>
   <div class="col-sm-3 col-md-3 navbar-div navSuperAdmin">
            <ul class="nav nav-sidebar">
              <li class="active"><a href="{% url 'helpmapp:mostrar_administradorGeneral' %}">Inicio <span class="sr-only">(current)</span></a></li>
              <li><a href="{% url 'helpmapp:buscarCentroAcopio' %}">Buscar centro de acopio</a></li>
              <li><a href="{% url 'helpmapp:mostrar_crearProducto' %}">Agregar producto<span class="pull-right showopacity glyphicon glyphicon-plus"></span></a></li>
              <li><a href="{% url 'helpmapp:mostrar_configCuenta' %}">Configuración</a></li>
              <li><a href="{% url 'helpmapp:mostrar_crearAdministrador' %}">Crear cuenta administrador</a></li>
              
            </ul>
       </div>
     
         {% block body %}

      {% endblock %}

   <footer class="col-md-12 footer">
         <p>Todos los derechos reservados. TAWS 2017.</p>
    </footer>
  </div>
   <script src="{% static 'js/tests/vendor/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.15/datatables.min.js"></script>


  {% block scripts %}
{% endblock %}
  </body>
</html>

helpmapp/templates/helpmapp/Administrador/superAdmin/buscarCentroAcopio.html
{% extends "helpmapp/Administrador/superAdmin/base.html" %}
{% load static %}
    {% block title %}HelpMapp-Admin:Buscar centro{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/verCentro-estilo.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/estiloBuscarCentro.css' %}"> 
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.15/datatables.min.css"/>

{% endblock %}
  {% block body %}
    <section class="col-sm-9 col-md-9">
       <div class="container col-sm-9 col-md-9 ">
          <h3>Buscar centro de acopio</h3>
          
          <h4 class="col-sm-5 locacion">Provincia:</h4>
          <h4 class="col-sm-5 locacion">Canton: </h4> 

          <form method="Post" class="form-vertical list" action="{% url 'helpmapp:buscarCentroAcopio' %}">
          {% csrf_token %}
            <div class="form-group col-sm-5 col-md-5 ">
              <select id="province" name="provincia" class="questionsList"></select>
            </div>
            <div class="form-group col-sm-5 col-md-5">
               <select id='city' name= "ciudad" class="questionsList"></select>
            </div>
            <div class="form-group col-sm-2 col-md-2" id="div_submit">
              <button type="submit" class="btn btn-primary" id="btn-submit">Buscar</button>
            </div>
          </form>
      </div>

<!--INICIO DE LA TABLA -->

    <div class="container col-sm-9 tabla-centros">
          <div class="row">
          <div class="col-md-12">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title">Lista de centros de acopio</h3>
                <div class="pull-right">
                  <span class="clickable filter" data-toggle="tooltip" title="Toggle table filter" data-container="body">
                    <i class="glyphicon glyphicon-filter"></i>
                  </span>
                </div>
              </div>
              <div class="panel-body">
                <input type="text" class="form-control" id="dev-table-filter" data-action="filter" data-filters="#dev-table" placeholder="Filter Developers" />
              </div>
              <table class="table table-hover" id="dev-table">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Nombre de centro</th>
                    <th>Ciudad</th>
                    <th>Observar centro</th>
                  </tr>
                </thead>
                <tbody id="tabla-upc">
                  
                </tbody>
                  {% if upc %}
                  {% for u in upc %}
                  <tr>
                    <td>{{u.id}}</td>
                    <td>{{u.nombre_upc}}</td>
                    <td>{{u.canton}}</td>
                    <td><a href="{% url 'helpmapp:mostrar_verCentro' id_centro=u.pk %}">Ver centro</a></td>
                  </tr>
                {% endfor %}
                {% else %}
                   
                {% endif %}  
                    

<!--                 <tbody>
                  <tr>
                    <td>1</td>
                    <td>Kilgore</td>
                    <td>Trout</td>
                    <td>kilgore</td>
                  </tr>
                  <tr>
                    <td>2</td>
                    <td>Bob</td>
                    <td>Loblaw</td>
                    <td>boblahblah</td>
                  </tr>
                  <tr>
                    <td>3</td>
                    <td>Holden</td>
                    <td>Caulfield</td>
                    <td>penceyreject</td>
                  </tr>
                </tbody> -->
              </table>
            </div>
          </div>

        </div>
      </div>

<!-- FIN DE TABLA -->

     </section>
     {% endblock %}     
    {% block scripts %}
    <script src="{% static 'js/listar_cda.js' %}"></script>
    <script src="{% static 'js/filtrar.js' %}"></script>
    <script src="{% static 'js/func-tabla.js' %}"></script>
{% endblock %}

helpmapp/templates/helpmapp/Administrador/superAdmin/configCuenta.html
{% extends "helpmapp/Administrador/superAdmin/base.html" %}
{% load static %}
    {% block title %}HelpMapp-Admin:Configurar cuenta{% endblock %}
{% block css %}{% endblock %}
        {% block body %}
     <section class="col-sm-9 col-md-9">
       <div class="container col-sm-9 col-md-9 ">
        <h3>Configuración de cuenta</h3>
        <form method="Post" class="form-horizontal" action="{% url 'helpmapp:mostrar_configCuenta' %}">
          {% csrf_token %}
          <div class="form-group">
            <label class="control-label col-sm-4" for="oldpass">Contraseña actual:</label>
            <div class="col-sm-6">
              {{ form.password_actual }}
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-4" for="newpass">Nueva contraseña:</label>
            <div class="col-sm-6">          
              {{ form.password }}
            </div>
          </div>
           <div class="form-group">
            <label class="control-label col-sm-4" for="pwd">Confirmar contraseña:</label>
            <div class="col-sm-6">          
              {{ form.confirm_password }}
            </div>
          </div>
          <div class="form-group">        
            <div class="col-sm-offset-2 col-sm-10" id="div_submit">
              <button type="submit" class="btn btn-primary" id="btn-submit">Confirmar</button>
            </div>
        </div>
        </form>
      </div>
      {% if mensaje %}
        <div>
          <p> {{mensaje}}</p>
        </div>
      {% else %}
        
      {% endif %} 
     </section>
          
     {% endblock %}

{% block scripts %} 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
{% endblock %}

helpmapp/templates/helpmapp/Administrador/superAdmin/crearAdmin.html
{% extends "helpmapp/Administrador/superAdmin/base.html" %}
{% load static %}
    {% block title %}HelpMapp-Admin:Crear admin{% endblock %}
{% block css %}
    <link href="{% static 'css/estiloCrearAdmin.css' %}" rel="stylesheet">
{% endblock %}  
     {% block body %}
     <section class="col-sm-9 col-md-9">
       <div class="container col-sm-9 col-md-9 ">
        <h3>Crear administrador</h3>
        <form method="Post" class="form-horizontal" action="{% url 'helpmapp:mostrar_crearAdministrador' %}">
        {% csrf_token %}
          <div class="form-group">
            <label class="control-label col-sm-4" for="oldpass">Nombre de usuario:</label>
            <div class="col-sm-6">
              {{ form.nombre_usuario }}
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-4" for="newpass">Contraseña:</label>
            <div class="col-sm-6">          
              {{ form.contrasena }}
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-4" for="oldpass2">Correo:</label>
            <div class="col-sm-6">
              {{ form.correo }}
            </div>
          </div>
          <div class="form-group">        
            <div class="col-sm-offset-2 col-sm-10" id="div_submit">
              <button type="submit" class="btn btn-primary" id="btn-submit">Crear</button>
            </div>
        </div>
        </form>
      </div>
     </section>

     {% endblock %}
       {% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    {% endblock %}

helpmapp/templates/helpmapp/Administrador/superAdmin/crearProducto.html
{% extends "helpmapp/Administrador/superAdmin/base.html" %}

{% load static %}

{% block title %} HelpMapp-Admin:Crear producto{% endblock %}


{% block css %}
    
    <link href="{%static 'css/crearProducto-estilo.css' %}" rel="stylesheet">
 {% endblock %}   

     {% block body %}
       <div class="container col-sm-9 col-md-9 ">
        <h3>Crear Producto</h3>
           
  <form method = 'Post'>
    {% csrf_token %}
    {{ form.errors }}
    {{ form.non_field_errors }}
    <div class="form-group row">
      <label for="nombre_producto" class="col-sm-2 col-form-label">Nombre del producto: </label>
      <div class="col-sm-5">
        <input type="text" class="form-control" id="nombre_producto" name="nombre_producto" placeholder="Croquetas de perro">
      </div>
    </div>

    <div class="form-group row">
            <label class="col-sm-2 col-form-label" for="lista-categorias">Categoria</label>
            <div class="col-sm-5">
              <select class="form-control" id="id_categoria" name="id_categoria">
                <option value="">-- Seleccione una opci&oacute;n --</option>
                <option value=1>Comida</option>
                <option value=2>Ropa</option>
                <option value=3>Agua</option>
              </select>
            </div>
    </div>
   
    <!-- <div class="form-group row">
      <label for="cantidad" class="col-sm-2 col-form-label">Cantidad:  </label>
      <div class="col-sm-2">
        <input type="number" class="form-control" id="cantidad" name="cantidad" placeholder="1">
      </div>
    </div> -->
    
    <input type="hidden" id="estado" name="estado" value=1>
    <div class="form-group row">
      <div class="offset-sm-2 col-sm-10 contenedor-submit">
        <input type="submit" name='submit' class="btn btn-primary" value='Crear producto'>
      </div>
    </div>
  </form>
      </div>
     
{% endblock %}

helpmapp/templates/helpmapp/Administrador/superAdmin/recuperarCuenta.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<p>sdfadsf</p>
</body>
</html>